service: lab4all-auth

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: dev
  profile: default

  environment:
    # Cognito
    USER_POOL_ID: us-east-1_R8nus0NoJ
    CLIENT_ID: 5ioefbupk9cl6eikb46aqqqn57

    # Dynamo tables (use these in code instead of hardcoded names)
    CLASSROOMS_TABLE: classrooms
    MEMBERSHIPS_TABLE: memberships
    SCHOOLS_TABLE: schools
    ANNOUNCEMENTS_TABLE: announcements
    EXPERIMENTS_TABLE: experiments

    # Buckets
    ANNOUNCEMENTS_BUCKET: announcements-lab4all
    EXPERIMENTS_BUCKET: experiments-lab4all

    # Feature flags (optional)
    STRICT_SCHOOL_SIGNUP: "true"

    # Presigned URLS TTL:
    SIGNED_URL_TTL: "600"

  iamRoleStatements:
    # ---------------- DynamoDB permissions ----------------
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:TransactWriteItems
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
      Resource:
        # classrooms
        - arn:aws:dynamodb:${self:provider.region}:529710251073:table/classrooms
        - arn:aws:dynamodb:${self:provider.region}:529710251073:table/classrooms/index/joinCode-index
        # memberships
        - arn:aws:dynamodb:${self:provider.region}:529710251073:table/memberships
        # schools (+ GSIs for browse/search)
        - arn:aws:dynamodb:${self:provider.region}:529710251073:table/schools
        - arn:aws:dynamodb:${self:provider.region}:529710251073:table/schools/index/countryCityName-index
        - arn:aws:dynamodb:${self:provider.region}:529710251073:table/schools/index/countryName-index
        - arn:aws:dynamodb:${self:provider.region}:529710251073:table/schools/index/globalName-index
        # announcements
        - arn:aws:dynamodb:${self:provider.region}:529710251073:table/announcements
        - arn:aws:dynamodb:${self:provider.region}:529710251073:table/announcements/index/announcementId-index
        - arn:aws:dynamodb:${self:provider.region}:529710251073:table/announcements/index/author-index
        # experiments
        - arn:aws:dynamodb:us-east-1:529710251073:table/experiments
        - arn:aws:dynamodb:us-east-1:529710251073:table/experiments/index/GSI1

    # ---------------- Cognito permissions ----------------
    - Effect: Allow
      Action:
        - cognito-idp:SignUp
        - cognito-idp:ConfirmSignUp
        - cognito-idp:InitiateAuth
        - cognito-idp:AdminGetUser
        - cognito-idp:ListUsers
        - cognito-idp:AdminUpdateUserAttributes
      Resource: "*"

    # ---------------- S3: announcements bucket ----------------
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::${self:provider.environment.ANNOUNCEMENTS_BUCKET}/*

    # ---------------- S3: experiments bucket (PUT/GET/DELETE) ----------------
    # Needed by:
    # - logExperiment: presign PUT (requires PutObject on target key)
    # - finishExperiment: headObject/existence check (requires GetObject)
    # - deleteExperiment: delete log object (requires DeleteObject)
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::${self:provider.environment.EXPERIMENTS_BUCKET}/*

functions:
  # ---------- Auth ----------
  signup:
    handler: dist/index.signupHandler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  login:
    handler: dist/index.loginHandler
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  profile:
    handler: dist/index.profileHandler
    events:
      - http:
          path: auth/profile
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  confirm:
    handler: dist/index.confirmHandler
    events:
      - http:
          path: auth/confirm
          method: post
          cors: true

  # ---------- Classroom ----------
  createClassroom:
    handler: dist/index.createClassroomHandler
    events:
      - http:
          path: classroom/create
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  joinClassroom:
    handler: dist/index.joinClassroomHandler
    events:
      - http:
          path: classroom/join
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  refreshJoinCode:
    handler: dist/index.refreshJoinCodeHandler
    events:
      - http:
          path: classroom/refreshjc
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  getClassrooms:
    handler: dist/index.getMyClassroomsHandler
    events:
      - http:
          path: classroom/list
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  getMembers:
    handler: dist/index.getMembersHandler
    events:
      - http:
          path: classroom/members
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  deleteMembership:
    handler: dist/index.deleteMembershipHandler
    events:
      - http:
          path: classroom/membership
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  kickStudent:
    handler: dist/index.kickStudentHandler
    events:
      - http:
          path: classroom/kick
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  # ---------- Schools ----------
  registerSchool:
    handler: dist/index.registerSchoolHandler
    events:
      - http:
          path: school/register
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  listSchools:
    handler: dist/index.listSchoolsHandler
    events:
      - http:
          path: schools
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true

  getSchool:
    handler: dist/index.getSchoolHandler
    events:
      - http:
          path: schools/{schoolId}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true

  # ---------- Announcements ----------
  createAnnouncement:
    handler: dist/index.createAnnouncementHandler
    events:
      - http:
          path: announcements/create
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  fetchAnnouncements:
    handler: dist/handlers/announcements/fetch.fetchAnnouncementsHandler
    events:
      - http:
          path: announcements/fetch
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  # ---------- Experiment ----------
  createExperiment:
    handler: dist/index.createExperimentHandler
    events:
      - http:
          path: experiments/create
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  logExperiment:
    handler: dist/index.logExperimentHandler
    events:
      - http:
          path: experiments/log
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  deleteExperiment:
    handler: dist/index.deleteExperimentHandler
    events:
      - http:
          path: experiments/delete
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  infoExperiment:
    handler: dist/index.getExperimentInfoHandler
    events:
      - http:
          path: experiments/info
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  listExperiments:
    handler: dist/index.listExperimentsHandler
    events:
      - http:
          path: experiments/list
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  toggleVisibilityExperiment:
    handler: dist/index.toggleVisibilityExperimentHandler
    events:
      - http:
          path: experiments/togglehide
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

  finishExperiment:
    handler: dist/index.finishExperimentHandler
    events:
      - http:
          path: experiments/finish
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:529710251073:userpool/${self:provider.environment.USER_POOL_ID}

plugins:
  - serverless-offline
